import type { Question } from '@/types';

export const questions: Question[] = [
  {
    id: 'name',
    type: 'input',
    icon: 'fas fa-hand-wave',
    title: "Let's get started!",
    subtitle: "What should we call you?",
    field: 'name',
    placeholder: 'Enter your first name',
    displayName: 'Name',
  },
  {
    id: 'income',
    type: 'multiple',
    icon: 'fas fa-briefcase',
    title: (name) => `Hi ${name}! What's your annual income?`,
    subtitle: 'Select your income bracket',
    field: 'income',
    displayName: 'Income',
    min: 1,
    max: 1,
    options: [
      { value: 'under3', label: 'Under ₹3 Lakhs', icon: 'fas fa-coins', minIncome: 200000 },
      { value: '3to5', label: '₹3 - 5 Lakhs', icon: 'fas fa-wallet', minIncome: 400000 },
      { value: '5to10', label: '₹5 - 10 Lakhs', icon: 'fas fa-money-bill-wave', minIncome: 750000 },
      { value: '10to15', label: '₹10 - 15 Lakhs', icon: 'fas fa-credit-card', minIncome: 1250000 },
      { value: '15to36', label: '₹15 - 36 Lakhs', icon: 'fas fa-building-columns', minIncome: 2000000 },
      { value: '36plus', label: 'Above ₹36 Lakhs', icon: 'fas fa-crown', minIncome: 3600000 },
    ],
  },
  {
    id: 'creditScore',
    type: 'multiple',
    icon: 'fas fa-chart-line',
    title: (name) => `Great, ${name}! Your credit score range?`,
    subtitle: 'Optional, but helps improve eligibility accuracy',
    field: 'creditScore',
    displayName: 'Credit Score',
    min: 1,
    max: 1,
    options: [
      { value: 'excellent', label: 'Excellent (750+)', icon: 'fas fa-star', score: 800 },
      { value: 'good', label: 'Good (700-749)', icon: 'fas fa-check-circle', score: 725 },
      { value: 'fair', label: 'Fair (650-699)', icon: 'fas fa-thumbs-up', score: 675 },
      { value: 'poor', label: 'Poor / Not sure', icon: 'fas fa-question-circle', score: 600 },
    ],
  },
  {
    id: 'existingCards',
    type: 'multiple',
    icon: 'fas fa-credit-card',
    title: (name) => `Nice! How many credit cards do you currently have?`,
    subtitle: 'This helps us assess your approval likelihood',
    field: 'existingCards',
    displayName: 'Existing Cards',
    min: 1,
    max: 1,
    options: [
      { value: '0', label: 'None - this will be my first', icon: 'fas fa-seedling', count: 0 },
      { value: '1', label: '1 card', icon: 'fas fa-bullseye', count: 1 },
      { value: '2-3', label: '2-3 cards', icon: 'fas fa-layer-group', count: 2 },
      { value: '4+', label: '4+ cards', icon: 'fas fa-trophy', count: 4 },
    ],
  },
  {
    id: 'spending',
    type: 'multiple',
    icon: 'fas fa-shopping-cart',
    title: (name) => `Perfect, ${name}! What are your top spending categories?`,
    subtitle: 'Select 2-4 categories where you spend the most',
    field: 'spendingCategories',
    displayName: 'Spending Categories',
    min: 2,
    max: 4,
    options: [
      { value: 'shopping', label: 'Online Shopping', icon: 'fas fa-shopping-cart' },
      { value: 'travel', label: 'Travel & Hotels', icon: 'fas fa-plane' },
      { value: 'dining', label: 'Dining & Food Delivery', icon: 'fas fa-utensils' },
      { value: 'groceries', label: 'Groceries', icon: 'fas fa-basket-shopping' },
      { value: 'fuel', label: 'Fuel', icon: 'fas fa-gas-pump' },
      { value: 'entertainment', label: 'Entertainment', icon: 'fas fa-film' },
      { value: 'bills', label: 'Bills & Utilities', icon: 'fas fa-file-invoice-dollar' },
      { value: 'luxury', label: 'Luxury & Fashion', icon: 'fas fa-gem' },
    ],
  },
  {
    id: 'monthlySpend',
    type: 'multiple',
    icon: 'fas fa-sack-dollar',
    title: (name) => `Good choices! What's your typical monthly card spend?`,
    subtitle: 'Used to calculate break-even and maximize your rewards',
    field: 'monthlySpend',
    displayName: 'Monthly Spend',
    min: 1,
    max: 1,
    options: [
      { value: 'under10k', label: 'Less than ₹10,000', icon: 'fas fa-money-bill', amount: 8000 },
      { value: '10to25k', label: '₹10,000 - ₹25,000', icon: 'fas fa-money-bill-wave', amount: 17500 },
      { value: '25to50k', label: '₹25,000 - ₹50,000', icon: 'fas fa-money-bills', amount: 37500 },
      { value: '50to100k', label: '₹50,000 - ₹1,00,000', icon: 'fas fa-sack-dollar', amount: 75000 },
      { value: '100kplus', label: '₹1,00,000+', icon: 'fas fa-hand-holding-dollar', amount: 150000 },
    ],
  },
  {
    id: 'paymentPreference',
    type: 'multiple',
    icon: 'fas fa-mobile-screen',
    title: (name) => `Almost done! Payment preferences?`,
    subtitle: 'How do you typically make payments? (select all that apply)',
    field: 'paymentPreference',
    displayName: 'Payment Preferences',
    min: 1,
    max: 4,
    options: [
      { value: 'card_swipe', label: 'Card swipe/tap at stores', icon: 'fas fa-credit-card' },
      { value: 'online', label: 'Online payments on websites', icon: 'fas fa-laptop' },
      { value: 'mobile_wallet', label: 'Mobile wallets (GPay, PhonePe)', icon: 'fas fa-mobile-screen' },
      { value: 'food_delivery', label: 'Food delivery apps', icon: 'fas fa-burger' },
      { value: 'ecommerce', label: 'E-commerce apps', icon: 'fas fa-shopping-bag' },
    ],
  },
  {
    id: 'goal',
    type: 'multiple',
    icon: 'fas fa-bullseye',
    title: (name) => `Last one, ${name}! What's your primary goal?`,
    subtitle: 'Select 1-2 goals that matter most to you',
    field: 'primaryGoal',
    displayName: 'Primary Goals',
    min: 1,
    max: 2,
    options: [
      { value: 'cashback', label: 'Maximum cashback', icon: 'fas fa-dollar-sign' },
      { value: 'rewards', label: 'Reward points', icon: 'fas fa-gift' },
      { value: 'travel', label: 'Travel benefits', icon: 'fas fa-plane-departure' },
      { value: 'lifestyle', label: 'Lifestyle perks', icon: 'fas fa-sparkles' },
      { value: 'lowfee', label: 'Lifetime free / Low fee', icon: 'fas fa-tag' },
    ],
  },
];
